### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by ik0** [20dec/nodejs-pool-api-monitor-site#1]
This script.js makes too many ajax requests. I think you should remove function calls from another function and leave only UpdateAllStats() to call other Update functions. With current version if i try it on my phone it gets hot ! I don't want SO live statistics :)

**Comment by 20dec** [comment]
Thanks for your feedback. I know this. But function call other function for the fast start-up display value. I don't think you use phone for a long time to get it's hot :( I think everyone will use phone for check it about 30 seconds to 1 minute for fast catching. And open on browser on PC or laptop will be smooth.
You can move function lines inside functions and set interval higher to make everything not so often. Beside that, I will think about your mind to improve it better.
Thanks again.
20dec

**Comment by ik0** [comment]
Hi, I've already optimize it for my needs. I prefer to open it in some browser tab and leave it there. If you open Chrome or Firefox networking debug tools. you will see how many requests and traffic it's make. The phone example was just how I found there is something wrong. Now my version just refresh everything once per 10sec. I don't need fast start, but long running performance. Maybe I'll fork this project, but my changes are trivial. Anyway thanks for good work !

**Comment by 20dec** [comment]
Glad to hear you like this. Anyway, I found a website which can convert web to android app, i make a try and feel it good. Maybe you will like it.
http://web2apk.com/create.aspx
Regards,
20dec

**Comment by ik0** [comment]
offtopic: did you check this Android app : https://play.google.com/store/apps/details?id=de.blindjerobine.supportxmrpool ? It's very good. I hope you can see it, because it's unreleased yet (i saw it on pool's chatbox).

**Comment by 20dec** [comment]
Not yet. I don't have reason to use it. I don't want my phone have a app which will run in background. I've had web monitor with all information in one click already :) And notification with email. You know, app push notification with block found still need run in background and network connection.
